host:
    replica_id: 3
    raft_address: "deployd3:21513"
    wal_dir: "/data"
    nodehost_dir: "/data"
    deployment_id: 0
    peer: 
        1: "deployd1:21511"
        2: "deployd2:21512"
        3: "deployd3:21513"
    clickhouse: 
        address: clickhouse-deployd3:9000
replica:
    1:
        bootstrap: false
        id: "deployd-v1"
        alias: "deployd Microservice (POC)"
        type: "deployd"
