host:
    replica_id: 2
    raft_address: "deployd2:21512"
    wal_dir: "/data"
    nodehost_dir: "/data"
    deployment_id: 0
    peer: 
        1: "deployd1:21511"
        2: "deployd2:21512"
        3: "deployd3:21513"
    clickhouse: 
        address: clickhouse-deployd2:9000
replica:
    1:
        bootstrap: false
        id: "deployd-v1"
        alias: "deployd Microservice (POC)"
        type: "deployd"
    2:
        bootstrap: false
        id: "artifactd-v1"
        alias: "artifactd Microservice (POC)"
        type: "artifactd"
    3:
        bootstrap: false
        id: "secretd-v1"
        alias: "secretd Microservice (POC)"
        type: "secretd"
