http:
  public:
    address: ":9600"
    fqdn: http://mb1

ui:
  dir: "/var/www"

storage:
  s3:
    blob:
      endpoint: d3580329dcd290336186304be108631f.r2.cloudflarestorage.com
      key_id: <secret>
      key_secret: <secret>
      use_ssl: true
      bucket_name: artifactd-beta
      base_public_url: https://mb1:9000/artifactd-beta
  clickhouse:
    content:
      address: "clickhouse-darurat:9000"
      username: <secret>
      password: <secret>
      database: default
      read_timeout: 2s
