name: Build & Deploy Go App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Hello"
        required: true
        default: "staging"

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      draft_tag: ${{ steps.draft_tag.outputs.draft_tag }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Test
        run: go test -v ./...

      - name: Build deployd and copy necessary files
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/deployd -v ./cmd/deployd/*.go
          cp ./config/deployd/*.yml dist
          cp -r ./www dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployd-archive
          path: dist/
          if-no-files-found: error

  deploy:
    needs: [build]     # <<< ensures job waits for build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: deployd-archive
          path: deploy-artifact

      - name: Show downloaded files (debug)
        run: ls -R deploy-artifact

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:desain-gratis-ci

      - name: Debug Tailscale
        run: |
          tailscale status
          tailscale ping mb1

      - name: Upload artifactd & metadata to private deployd repository
        uses: desain-gratis/deployd-gh-action@latest
        with:
          url: http://mb1:9600
          namespace: desain-gratis
          name: user-profile
          archive: deploy-artifact
